### ISSUE TITLE
Code works for 1.9.3

### ISSUE THREAD

**Issue by jgn** [gnilrets/envcrypt#1]
Hi. Do you think you could loosen the Ruby requirements for this gem to allow 1.9.3?

The only Ruby 2ism are in one method definition where the following works and passes specs:

https://github.com/IoraHealth/envcrypt/blob/jn-allow_1.9.3/lib/envcrypt/envcrypt.rb#L20

**Comment by gnilrets** [comment]
Sure thing - #2 .  The gem is now available as 0.1.1.
