### ISSUE TITLE
0.1.1 doesn't work with Ruby 2+, breaks Birst_Command

### ISSUE THREAD

**Issue by mandavilli** [gnilrets/envcrypt#3]
``` ruby
s.required_ruby_version = '~> 1.9.3'
```

Birst_Command expects Ruby 2.0.0+ and refers to this gem (which was fine, prior to v0.1.1). I think you meant to put `>=1.9.3` ?

**Comment by gnilrets** [comment]
Resolved with version 0.1.2.  Thanks!
